// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package adapters

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/therenotomorrow/gotes/internal/domain/entities"
	"github.com/therenotomorrow/gotes/internal/domain/types/id"
)

// NewMockNotesRepository creates a new instance of MockNotesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotesRepository {
	mock := &MockNotesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotesRepository is an autogenerated mock type for the NotesRepository type
type MockNotesRepository struct {
	mock.Mock
}

type MockNotesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotesRepository) EXPECT() *MockNotesRepository_Expecter {
	return &MockNotesRepository_Expecter{mock: &_m.Mock}
}

// DeleteNote provides a mock function for the type MockNotesRepository
func (_mock *MockNotesRepository) DeleteNote(ctx context.Context, note *entities.Note) error {
	ret := _mock.Called(ctx, note)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNote")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Note) error); ok {
		r0 = returnFunc(ctx, note)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotesRepository_DeleteNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNote'
type MockNotesRepository_DeleteNote_Call struct {
	*mock.Call
}

// DeleteNote is a helper method to define mock.On call
//   - ctx context.Context
//   - note *entities.Note
func (_e *MockNotesRepository_Expecter) DeleteNote(ctx interface{}, note interface{}) *MockNotesRepository_DeleteNote_Call {
	return &MockNotesRepository_DeleteNote_Call{Call: _e.mock.On("DeleteNote", ctx, note)}
}

func (_c *MockNotesRepository_DeleteNote_Call) Run(run func(ctx context.Context, note *entities.Note)) *MockNotesRepository_DeleteNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Note
		if args[1] != nil {
			arg1 = args[1].(*entities.Note)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotesRepository_DeleteNote_Call) Return(err error) *MockNotesRepository_DeleteNote_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotesRepository_DeleteNote_Call) RunAndReturn(run func(ctx context.Context, note *entities.Note) error) *MockNotesRepository_DeleteNote_Call {
	_c.Call.Return(run)
	return _c
}

// GetNote provides a mock function for the type MockNotesRepository
func (_mock *MockNotesRepository) GetNote(ctx context.Context, id1 id.ID) (*entities.Note, error) {
	ret := _mock.Called(ctx, id1)

	if len(ret) == 0 {
		panic("no return value specified for GetNote")
	}

	var r0 *entities.Note
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, id.ID) (*entities.Note, error)); ok {
		return returnFunc(ctx, id1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, id.ID) *entities.Note); ok {
		r0 = returnFunc(ctx, id1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Note)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, id.ID) error); ok {
		r1 = returnFunc(ctx, id1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesRepository_GetNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNote'
type MockNotesRepository_GetNote_Call struct {
	*mock.Call
}

// GetNote is a helper method to define mock.On call
//   - ctx context.Context
//   - id1 id.ID
func (_e *MockNotesRepository_Expecter) GetNote(ctx interface{}, id1 interface{}) *MockNotesRepository_GetNote_Call {
	return &MockNotesRepository_GetNote_Call{Call: _e.mock.On("GetNote", ctx, id1)}
}

func (_c *MockNotesRepository_GetNote_Call) Run(run func(ctx context.Context, id1 id.ID)) *MockNotesRepository_GetNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 id.ID
		if args[1] != nil {
			arg1 = args[1].(id.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotesRepository_GetNote_Call) Return(note *entities.Note, err error) *MockNotesRepository_GetNote_Call {
	_c.Call.Return(note, err)
	return _c
}

func (_c *MockNotesRepository_GetNote_Call) RunAndReturn(run func(ctx context.Context, id1 id.ID) (*entities.Note, error)) *MockNotesRepository_GetNote_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotesByUser provides a mock function for the type MockNotesRepository
func (_mock *MockNotesRepository) GetNotesByUser(ctx context.Context, user *entities.User) ([]*entities.Note, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for GetNotesByUser")
	}

	var r0 []*entities.Note
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) ([]*entities.Note, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) []*entities.Note); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Note)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesRepository_GetNotesByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotesByUser'
type MockNotesRepository_GetNotesByUser_Call struct {
	*mock.Call
}

// GetNotesByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entities.User
func (_e *MockNotesRepository_Expecter) GetNotesByUser(ctx interface{}, user interface{}) *MockNotesRepository_GetNotesByUser_Call {
	return &MockNotesRepository_GetNotesByUser_Call{Call: _e.mock.On("GetNotesByUser", ctx, user)}
}

func (_c *MockNotesRepository_GetNotesByUser_Call) Run(run func(ctx context.Context, user *entities.User)) *MockNotesRepository_GetNotesByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.User
		if args[1] != nil {
			arg1 = args[1].(*entities.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotesRepository_GetNotesByUser_Call) Return(notes []*entities.Note, err error) *MockNotesRepository_GetNotesByUser_Call {
	_c.Call.Return(notes, err)
	return _c
}

func (_c *MockNotesRepository_GetNotesByUser_Call) RunAndReturn(run func(ctx context.Context, user *entities.User) ([]*entities.Note, error)) *MockNotesRepository_GetNotesByUser_Call {
	_c.Call.Return(run)
	return _c
}

// SaveNote provides a mock function for the type MockNotesRepository
func (_mock *MockNotesRepository) SaveNote(ctx context.Context, note *entities.Note) (*entities.Note, error) {
	ret := _mock.Called(ctx, note)

	if len(ret) == 0 {
		panic("no return value specified for SaveNote")
	}

	var r0 *entities.Note
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Note) (*entities.Note, error)); ok {
		return returnFunc(ctx, note)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Note) *entities.Note); ok {
		r0 = returnFunc(ctx, note)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Note)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.Note) error); ok {
		r1 = returnFunc(ctx, note)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesRepository_SaveNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveNote'
type MockNotesRepository_SaveNote_Call struct {
	*mock.Call
}

// SaveNote is a helper method to define mock.On call
//   - ctx context.Context
//   - note *entities.Note
func (_e *MockNotesRepository_Expecter) SaveNote(ctx interface{}, note interface{}) *MockNotesRepository_SaveNote_Call {
	return &MockNotesRepository_SaveNote_Call{Call: _e.mock.On("SaveNote", ctx, note)}
}

func (_c *MockNotesRepository_SaveNote_Call) Run(run func(ctx context.Context, note *entities.Note)) *MockNotesRepository_SaveNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Note
		if args[1] != nil {
			arg1 = args[1].(*entities.Note)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotesRepository_SaveNote_Call) Return(note1 *entities.Note, err error) *MockNotesRepository_SaveNote_Call {
	_c.Call.Return(note1, err)
	return _c
}

func (_c *MockNotesRepository_SaveNote_Call) RunAndReturn(run func(ctx context.Context, note *entities.Note) (*entities.Note, error)) *MockNotesRepository_SaveNote_Call {
	_c.Call.Return(run)
	return _c
}
