// Code generated by protoc-gen-verbose. DO NOT EDIT.
// source: api/metrics/v1/messages.proto

package v1

import (
	fmt "fmt"
)

func (x *UploadMetricsRequest) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadMetricsRequest<Requests=%v, Errors=%v>", x.Requests, x.Errors)
}

func (x *UploadMetricsResponse) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadMetricsResponse<Total=%v, ErrorRate=%v>", x.Total, x.ErrorRate)
}
