// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/metrics/v1/messages.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UploadMetricsRequest is the request message for uploading client-side metrics.
type UploadMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of requests performed by the client.
	Requests int64 `protobuf:"varint,1,opt,name=requests,proto3" json:"requests,omitempty"`
	// Total number of errors encountered during requests.
	Errors        int64 `protobuf:"varint,2,opt,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMetricsRequest) Reset() {
	*x = UploadMetricsRequest{}
	mi := &file_api_metrics_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetricsRequest) ProtoMessage() {}

func (x *UploadMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metrics_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetricsRequest.ProtoReflect.Descriptor instead.
func (*UploadMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_metrics_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *UploadMetricsRequest) GetRequests() int64 {
	if x != nil {
		return x.Requests
	}
	return 0
}

func (x *UploadMetricsRequest) GetErrors() int64 {
	if x != nil {
		return x.Errors
	}
	return 0
}

// UploadMetricsResponse is the response message after processing metrics.
type UploadMetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total accumulated number of requests performed by the client.
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// Calculated error rate (errors divided by total requests).
	ErrorRate     float64 `protobuf:"fixed64,3,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMetricsResponse) Reset() {
	*x = UploadMetricsResponse{}
	mi := &file_api_metrics_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetricsResponse) ProtoMessage() {}

func (x *UploadMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metrics_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetricsResponse.ProtoReflect.Descriptor instead.
func (*UploadMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_metrics_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMetricsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UploadMetricsResponse) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

var File_api_metrics_v1_messages_proto protoreflect.FileDescriptor

const file_api_metrics_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/metrics/v1/messages.proto\x12\x0eapi.metrics.v1\"J\n" +
	"\x14UploadMetricsRequest\x12\x1a\n" +
	"\brequests\x18\x01 \x01(\x03R\brequests\x12\x16\n" +
	"\x06errors\x18\x02 \x01(\x03R\x06errors\"L\n" +
	"\x15UploadMetricsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x03 \x01(\x01R\terrorRateB5Z3github.com/therenotomorrow/gotes/pkg/api/metrics/v1b\x06proto3"

var (
	file_api_metrics_v1_messages_proto_rawDescOnce sync.Once
	file_api_metrics_v1_messages_proto_rawDescData []byte
)

func file_api_metrics_v1_messages_proto_rawDescGZIP() []byte {
	file_api_metrics_v1_messages_proto_rawDescOnce.Do(func() {
		file_api_metrics_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_metrics_v1_messages_proto_rawDesc), len(file_api_metrics_v1_messages_proto_rawDesc)))
	})
	return file_api_metrics_v1_messages_proto_rawDescData
}

var file_api_metrics_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_metrics_v1_messages_proto_goTypes = []any{
	(*UploadMetricsRequest)(nil),  // 0: api.metrics.v1.UploadMetricsRequest
	(*UploadMetricsResponse)(nil), // 1: api.metrics.v1.UploadMetricsResponse
}
var file_api_metrics_v1_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_metrics_v1_messages_proto_init() }
func file_api_metrics_v1_messages_proto_init() {
	if File_api_metrics_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_metrics_v1_messages_proto_rawDesc), len(file_api_metrics_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_metrics_v1_messages_proto_goTypes,
		DependencyIndexes: file_api_metrics_v1_messages_proto_depIdxs,
		MessageInfos:      file_api_metrics_v1_messages_proto_msgTypes,
	}.Build()
	File_api_metrics_v1_messages_proto = out.File
	file_api_metrics_v1_messages_proto_goTypes = nil
	file_api_metrics_v1_messages_proto_depIdxs = nil
}
