// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/metrics/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_metrics_v1_service_proto protoreflect.FileDescriptor

const file_api_metrics_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1capi/metrics/v1/service.proto\x12\x0eapi.metrics.v1\x1a\x1dapi/metrics/v1/messages.proto2p\n" +
	"\x0eMetricsService\x12^\n" +
	"\rUploadMetrics\x12$.api.metrics.v1.UploadMetricsRequest\x1a%.api.metrics.v1.UploadMetricsResponse(\x01B5Z3github.com/therenotomorrow/gotes/pkg/api/metrics/v1b\x06proto3"

var file_api_metrics_v1_service_proto_goTypes = []any{
	(*UploadMetricsRequest)(nil),  // 0: api.metrics.v1.UploadMetricsRequest
	(*UploadMetricsResponse)(nil), // 1: api.metrics.v1.UploadMetricsResponse
}
var file_api_metrics_v1_service_proto_depIdxs = []int32{
	0, // 0: api.metrics.v1.MetricsService.UploadMetrics:input_type -> api.metrics.v1.UploadMetricsRequest
	1, // 1: api.metrics.v1.MetricsService.UploadMetrics:output_type -> api.metrics.v1.UploadMetricsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_metrics_v1_service_proto_init() }
func file_api_metrics_v1_service_proto_init() {
	if File_api_metrics_v1_service_proto != nil {
		return
	}
	file_api_metrics_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_metrics_v1_service_proto_rawDesc), len(file_api_metrics_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_metrics_v1_service_proto_goTypes,
		DependencyIndexes: file_api_metrics_v1_service_proto_depIdxs,
	}.Build()
	File_api_metrics_v1_service_proto = out.File
	file_api_metrics_v1_service_proto_goTypes = nil
	file_api_metrics_v1_service_proto_depIdxs = nil
}
