// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"
)

type Querier interface {
	SelectNote(ctx context.Context, id int64) (*Note, error)
	SelectNotes(ctx context.Context) ([]*Note, error)
}

var _ Querier = (*Queries)(nil)
