// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: select_notes.sql

package queries

import (
	"context"
)

const selectNotes = `-- name: SelectNotes :many
SELECT id, title, content, created_at, updated_at
FROM notes
ORDER BY id
`

func (q *Queries) SelectNotes(ctx context.Context) ([]*Note, error) {
	rows, err := q.db.Query(ctx, selectNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
