// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/therenotomorrow/gotes/internal/domain/entities"
)

// NewMockEventsRepository creates a new instance of MockEventsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventsRepository {
	mock := &MockEventsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventsRepository is an autogenerated mock type for the EventsRepository type
type MockEventsRepository struct {
	mock.Mock
}

type MockEventsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventsRepository) EXPECT() *MockEventsRepository_Expecter {
	return &MockEventsRepository_Expecter{mock: &_m.Mock}
}

// CountEvents provides a mock function for the type MockEventsRepository
func (_mock *MockEventsRepository) CountEvents(ctx context.Context, user *entities.User) (int32, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CountEvents")
	}

	var r0 int32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) (int32, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) int32); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventsRepository_CountEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountEvents'
type MockEventsRepository_CountEvents_Call struct {
	*mock.Call
}

// CountEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entities.User
func (_e *MockEventsRepository_Expecter) CountEvents(ctx interface{}, user interface{}) *MockEventsRepository_CountEvents_Call {
	return &MockEventsRepository_CountEvents_Call{Call: _e.mock.On("CountEvents", ctx, user)}
}

func (_c *MockEventsRepository_CountEvents_Call) Run(run func(ctx context.Context, user *entities.User)) *MockEventsRepository_CountEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.User
		if args[1] != nil {
			arg1 = args[1].(*entities.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventsRepository_CountEvents_Call) Return(n int32, err error) *MockEventsRepository_CountEvents_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockEventsRepository_CountEvents_Call) RunAndReturn(run func(ctx context.Context, user *entities.User) (int32, error)) *MockEventsRepository_CountEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvent provides a mock function for the type MockEventsRepository
func (_mock *MockEventsRepository) GetEvent(ctx context.Context, user *entities.User) (*entities.Event, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for GetEvent")
	}

	var r0 *entities.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) (*entities.Event, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) *entities.Event); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventsRepository_GetEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvent'
type MockEventsRepository_GetEvent_Call struct {
	*mock.Call
}

// GetEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entities.User
func (_e *MockEventsRepository_Expecter) GetEvent(ctx interface{}, user interface{}) *MockEventsRepository_GetEvent_Call {
	return &MockEventsRepository_GetEvent_Call{Call: _e.mock.On("GetEvent", ctx, user)}
}

func (_c *MockEventsRepository_GetEvent_Call) Run(run func(ctx context.Context, user *entities.User)) *MockEventsRepository_GetEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.User
		if args[1] != nil {
			arg1 = args[1].(*entities.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventsRepository_GetEvent_Call) Return(event *entities.Event, err error) *MockEventsRepository_GetEvent_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockEventsRepository_GetEvent_Call) RunAndReturn(run func(ctx context.Context, user *entities.User) (*entities.Event, error)) *MockEventsRepository_GetEvent_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEvent provides a mock function for the type MockEventsRepository
func (_mock *MockEventsRepository) SaveEvent(ctx context.Context, event *entities.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for SaveEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventsRepository_SaveEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEvent'
type MockEventsRepository_SaveEvent_Call struct {
	*mock.Call
}

// SaveEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event *entities.Event
func (_e *MockEventsRepository_Expecter) SaveEvent(ctx interface{}, event interface{}) *MockEventsRepository_SaveEvent_Call {
	return &MockEventsRepository_SaveEvent_Call{Call: _e.mock.On("SaveEvent", ctx, event)}
}

func (_c *MockEventsRepository_SaveEvent_Call) Run(run func(ctx context.Context, event *entities.Event)) *MockEventsRepository_SaveEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Event
		if args[1] != nil {
			arg1 = args[1].(*entities.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventsRepository_SaveEvent_Call) Return(err error) *MockEventsRepository_SaveEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventsRepository_SaveEvent_Call) RunAndReturn(run func(ctx context.Context, event *entities.Event) error) *MockEventsRepository_SaveEvent_Call {
	_c.Call.Return(run)
	return _c
}
