// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/therenotomorrow/gotes/internal/api/chat/v1/entities"
)

// NewMockMessagesRepository creates a new instance of MockMessagesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessagesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessagesRepository {
	mock := &MockMessagesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessagesRepository is an autogenerated mock type for the MessagesRepository type
type MockMessagesRepository struct {
	mock.Mock
}

type MockMessagesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessagesRepository) EXPECT() *MockMessagesRepository_Expecter {
	return &MockMessagesRepository_Expecter{mock: &_m.Mock}
}

// DeleteMessage provides a mock function for the type MockMessagesRepository
func (_mock *MockMessagesRepository) DeleteMessage(ctx context.Context, message *entities.Message) error {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Message) error); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessagesRepository_DeleteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessage'
type MockMessagesRepository_DeleteMessage_Call struct {
	*mock.Call
}

// DeleteMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - message *entities.Message
func (_e *MockMessagesRepository_Expecter) DeleteMessage(ctx interface{}, message interface{}) *MockMessagesRepository_DeleteMessage_Call {
	return &MockMessagesRepository_DeleteMessage_Call{Call: _e.mock.On("DeleteMessage", ctx, message)}
}

func (_c *MockMessagesRepository_DeleteMessage_Call) Run(run func(ctx context.Context, message *entities.Message)) *MockMessagesRepository_DeleteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Message
		if args[1] != nil {
			arg1 = args[1].(*entities.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessagesRepository_DeleteMessage_Call) Return(err error) *MockMessagesRepository_DeleteMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessagesRepository_DeleteMessage_Call) RunAndReturn(run func(ctx context.Context, message *entities.Message) error) *MockMessagesRepository_DeleteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// Outbox provides a mock function for the type MockMessagesRepository
func (_mock *MockMessagesRepository) Outbox(ctx context.Context) ([]*entities.Message, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Outbox")
	}

	var r0 []*entities.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entities.Message, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entities.Message); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessagesRepository_Outbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Outbox'
type MockMessagesRepository_Outbox_Call struct {
	*mock.Call
}

// Outbox is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMessagesRepository_Expecter) Outbox(ctx interface{}) *MockMessagesRepository_Outbox_Call {
	return &MockMessagesRepository_Outbox_Call{Call: _e.mock.On("Outbox", ctx)}
}

func (_c *MockMessagesRepository_Outbox_Call) Run(run func(ctx context.Context)) *MockMessagesRepository_Outbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessagesRepository_Outbox_Call) Return(messages []*entities.Message, err error) *MockMessagesRepository_Outbox_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockMessagesRepository_Outbox_Call) RunAndReturn(run func(ctx context.Context) ([]*entities.Message, error)) *MockMessagesRepository_Outbox_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMessage provides a mock function for the type MockMessagesRepository
func (_mock *MockMessagesRepository) SaveMessage(ctx context.Context, message *entities.Message) error {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for SaveMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Message) error); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessagesRepository_SaveMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMessage'
type MockMessagesRepository_SaveMessage_Call struct {
	*mock.Call
}

// SaveMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - message *entities.Message
func (_e *MockMessagesRepository_Expecter) SaveMessage(ctx interface{}, message interface{}) *MockMessagesRepository_SaveMessage_Call {
	return &MockMessagesRepository_SaveMessage_Call{Call: _e.mock.On("SaveMessage", ctx, message)}
}

func (_c *MockMessagesRepository_SaveMessage_Call) Run(run func(ctx context.Context, message *entities.Message)) *MockMessagesRepository_SaveMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Message
		if args[1] != nil {
			arg1 = args[1].(*entities.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessagesRepository_SaveMessage_Call) Return(err error) *MockMessagesRepository_SaveMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessagesRepository_SaveMessage_Call) RunAndReturn(run func(ctx context.Context, message *entities.Message) error) *MockMessagesRepository_SaveMessage_Call {
	_c.Call.Return(run)
	return _c
}
