// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/therenotomorrow/gotes/internal/api/chat/v1/ports"
)

// NewMockStoreProvider creates a new instance of MockStoreProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoreProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoreProvider {
	mock := &MockStoreProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStoreProvider is an autogenerated mock type for the StoreProvider type
type MockStoreProvider struct {
	mock.Mock
}

type MockStoreProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStoreProvider) EXPECT() *MockStoreProvider_Expecter {
	return &MockStoreProvider_Expecter{mock: &_m.Mock}
}

// Provide provides a mock function for the type MockStoreProvider
func (_mock *MockStoreProvider) Provide(ctx context.Context) ports.Store {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Provide")
	}

	var r0 ports.Store
	if returnFunc, ok := ret.Get(0).(func(context.Context) ports.Store); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(ports.Store)
	}
	return r0
}

// MockStoreProvider_Provide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provide'
type MockStoreProvider_Provide_Call struct {
	*mock.Call
}

// Provide is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStoreProvider_Expecter) Provide(ctx interface{}) *MockStoreProvider_Provide_Call {
	return &MockStoreProvider_Provide_Call{Call: _e.mock.On("Provide", ctx)}
}

func (_c *MockStoreProvider_Provide_Call) Run(run func(ctx context.Context)) *MockStoreProvider_Provide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStoreProvider_Provide_Call) Return(store ports.Store) *MockStoreProvider_Provide_Call {
	_c.Call.Return(store)
	return _c
}

func (_c *MockStoreProvider_Provide_Call) RunAndReturn(run func(ctx context.Context) ports.Store) *MockStoreProvider_Provide_Call {
	_c.Call.Return(run)
	return _c
}
