pkgname: mocks
template: testify
filename: "{{ .InterfaceName | lower }}.go"
packages:
  github.com/therenotomorrow/gotes/internal/api/notes/v1/ports:
    config:
      dir: internal/api/notes/v1/mocks
    interfaces:
      NotesRepository: {}
      UnitOfWork: {}
      Store: {}
