// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_user.sql

package commands

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertUser = `-- name: InsertUser :one
INSERT INTO users(name, email, password, token, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertUserParams struct {
	Name      string    `db:"name"`
	Email     string    `db:"email"`
	Password  string    `db:"password"`
	Token     uuid.UUID `db:"token"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

func (q *Queries) InsertUser(ctx context.Context, arg *InsertUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Token,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
