// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package commands

import (
	"context"
)

type Querier interface {
	InsertUser(ctx context.Context, arg *InsertUserParams) (int64, error)
	UpdateUser(ctx context.Context, arg *UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
