// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_user.sql

package commands

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name       = $1,
    email      = $2,
    password   = $3,
    token      = $4,
    updated_at = $5
WHERE id = $6
`

type UpdateUserParams struct {
	Name      string    `db:"name"`
	Email     string    `db:"email"`
	Password  string    `db:"password"`
	Token     uuid.UUID `db:"token"`
	UpdatedAt time.Time `db:"updated_at"`
	ID        int64     `db:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg *UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Token,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
