// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package adapters

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/therenotomorrow/gotes/internal/api/users/v1/ports"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Users provides a mock function for the type MockStore
func (_mock *MockStore) Users() ports.UsersRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Users")
	}

	var r0 ports.UsersRepository
	if returnFunc, ok := ret.Get(0).(func() ports.UsersRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.UsersRepository)
		}
	}
	return r0
}

// MockStore_Users_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Users'
type MockStore_Users_Call struct {
	*mock.Call
}

// Users is a helper method to define mock.On call
func (_e *MockStore_Expecter) Users() *MockStore_Users_Call {
	return &MockStore_Users_Call{Call: _e.mock.On("Users")}
}

func (_c *MockStore_Users_Call) Run(run func()) *MockStore_Users_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Users_Call) Return(usersRepository ports.UsersRepository) *MockStore_Users_Call {
	_c.Call.Return(usersRepository)
	return _c
}

func (_c *MockStore_Users_Call) RunAndReturn(run func() ports.UsersRepository) *MockStore_Users_Call {
	_c.Call.Return(run)
	return _c
}
