// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package adapters

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/therenotomorrow/gotes/internal/domain/entities"
	"github.com/therenotomorrow/gotes/internal/domain/types/email"
)

// NewMockUsersRepository creates a new instance of MockUsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersRepository {
	mock := &MockUsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersRepository is an autogenerated mock type for the UsersRepository type
type MockUsersRepository struct {
	mock.Mock
}

type MockUsersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersRepository) EXPECT() *MockUsersRepository_Expecter {
	return &MockUsersRepository_Expecter{mock: &_m.Mock}
}

// GetUserByEmail provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUserByEmail(ctx context.Context, mail email.Email) (*entities.User, error) {
	ret := _mock.Called(ctx, mail)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, email.Email) (*entities.User, error)); ok {
		return returnFunc(ctx, mail)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, email.Email) *entities.User); ok {
		r0 = returnFunc(ctx, mail)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, email.Email) error); ok {
		r1 = returnFunc(ctx, mail)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUsersRepository_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - mail email.Email
func (_e *MockUsersRepository_Expecter) GetUserByEmail(ctx interface{}, mail interface{}) *MockUsersRepository_GetUserByEmail_Call {
	return &MockUsersRepository_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, mail)}
}

func (_c *MockUsersRepository_GetUserByEmail_Call) Run(run func(ctx context.Context, mail email.Email)) *MockUsersRepository_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 email.Email
		if args[1] != nil {
			arg1 = args[1].(email.Email)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUserByEmail_Call) Return(user *entities.User, err error) *MockUsersRepository_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, mail email.Email) (*entities.User, error)) *MockUsersRepository_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) SaveUser(ctx context.Context, user *entities.User) (*entities.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) (*entities.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) *entities.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type MockUsersRepository_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entities.User
func (_e *MockUsersRepository_Expecter) SaveUser(ctx interface{}, user interface{}) *MockUsersRepository_SaveUser_Call {
	return &MockUsersRepository_SaveUser_Call{Call: _e.mock.On("SaveUser", ctx, user)}
}

func (_c *MockUsersRepository_SaveUser_Call) Run(run func(ctx context.Context, user *entities.User)) *MockUsersRepository_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.User
		if args[1] != nil {
			arg1 = args[1].(*entities.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_SaveUser_Call) Return(user1 *entities.User, err error) *MockUsersRepository_SaveUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUsersRepository_SaveUser_Call) RunAndReturn(run func(ctx context.Context, user *entities.User) (*entities.User, error)) *MockUsersRepository_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) UpdateUser(ctx context.Context, user *entities.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersRepository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUsersRepository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entities.User
func (_e *MockUsersRepository_Expecter) UpdateUser(ctx interface{}, user interface{}) *MockUsersRepository_UpdateUser_Call {
	return &MockUsersRepository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, user)}
}

func (_c *MockUsersRepository_UpdateUser_Call) Run(run func(ctx context.Context, user *entities.User)) *MockUsersRepository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.User
		if args[1] != nil {
			arg1 = args[1].(*entities.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_UpdateUser_Call) Return(err error) *MockUsersRepository_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersRepository_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, user *entities.User) error) *MockUsersRepository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
