// Code generated by protoc-gen-verbose. DO NOT EDIT.
// source: api/users/v1/messages.proto

package v1

import (
	fmt "fmt"
)

func (x *User) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User<Id=%v, Name=%v, Email=%v>", x.Id, x.Name, x.Email)
}

func (x *RegisterUserRequest) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterUserRequest<Name=%v, Email=%v>", x.Name, x.Email)
}

func (x *RegisterUserResponse) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterUserResponse<User=%v>", x.User)
}

func (x *RefreshTokenRequest) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshTokenRequest<Email=%v, Password=%v>", x.Email, x.Password)
}

func (x *RefreshTokenResponse) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshTokenResponse<User=%v>", x.User)
}
