// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/users/v1/messages.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	types "github.com/therenotomorrow/gotes/pkg/api/types"
	_ "github.com/therenotomorrow/gotes/plugin/verbose/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User represents a single user entity.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the user.
	Id *types.ID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Display name of the user.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Email address of the user.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// Authentication token associated with the user.
	Token         string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_users_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() *types.ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// RegisterUserRequest is the request message for user registration.
type RegisterUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Display name of the new user.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Email address used for user identification and login.
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// Plain-text password provided during registration.
	//
	// This value is never stored directly and is expected to be
	// securely hashed by the server.
	Password      string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_api_users_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// RegisterUserResponse is the response message after successful user registration.
type RegisterUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The registered user with generated ID and authentication token.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_api_users_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// RefreshTokenRequest is the request message for refreshing an authentication token.
type RefreshTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Email address associated with the user.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Plain-text password used to re-authenticate the user.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_api_users_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RefreshTokenRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// RefreshTokenResponse is the response message after refreshing an authentication token.
type RefreshTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user with a newly issued authentication token.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_api_users_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_api_users_v1_messages_proto protoreflect.FileDescriptor

const file_api_users_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/users/v1/messages.proto\x12\fapi.users.v1\x1a\x12api/types/id.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1fplugin/verbose/v1/options.proto\"k\n" +
	"\x04User\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.api.types.IDR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\x05token\x18\x04 \x01(\tB\x04\x80\xb5\x18\x01R\x05token\"w\n" +
	"\x13RegisterUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\x05email\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02`\x01R\x05email\x12*\n" +
	"\bpassword\x18\x03 \x01(\tB\x0e\xbaH\a\xc8\x01\x01r\x02\x10\b\x80\xb5\x18\x01R\bpassword\">\n" +
	"\x14RegisterUserResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.api.users.v1.UserR\x04user\"c\n" +
	"\x13RefreshTokenRequest\x12 \n" +
	"\x05email\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02`\x01R\x05email\x12*\n" +
	"\bpassword\x18\x02 \x01(\tB\x0e\xbaH\a\xc8\x01\x01r\x02\x10\b\x80\xb5\x18\x01R\bpassword\">\n" +
	"\x14RefreshTokenResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.api.users.v1.UserR\x04userB3Z1github.com/therenotomorrow/gotes/pkg/api/users/v1b\x06proto3"

var (
	file_api_users_v1_messages_proto_rawDescOnce sync.Once
	file_api_users_v1_messages_proto_rawDescData []byte
)

func file_api_users_v1_messages_proto_rawDescGZIP() []byte {
	file_api_users_v1_messages_proto_rawDescOnce.Do(func() {
		file_api_users_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_users_v1_messages_proto_rawDesc), len(file_api_users_v1_messages_proto_rawDesc)))
	})
	return file_api_users_v1_messages_proto_rawDescData
}

var file_api_users_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_users_v1_messages_proto_goTypes = []any{
	(*User)(nil),                 // 0: api.users.v1.User
	(*RegisterUserRequest)(nil),  // 1: api.users.v1.RegisterUserRequest
	(*RegisterUserResponse)(nil), // 2: api.users.v1.RegisterUserResponse
	(*RefreshTokenRequest)(nil),  // 3: api.users.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil), // 4: api.users.v1.RefreshTokenResponse
	(*types.ID)(nil),             // 5: api.types.ID
}
var file_api_users_v1_messages_proto_depIdxs = []int32{
	5, // 0: api.users.v1.User.id:type_name -> api.types.ID
	0, // 1: api.users.v1.RegisterUserResponse.user:type_name -> api.users.v1.User
	0, // 2: api.users.v1.RefreshTokenResponse.user:type_name -> api.users.v1.User
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_users_v1_messages_proto_init() }
func file_api_users_v1_messages_proto_init() {
	if File_api_users_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_users_v1_messages_proto_rawDesc), len(file_api_users_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_users_v1_messages_proto_goTypes,
		DependencyIndexes: file_api_users_v1_messages_proto_depIdxs,
		MessageInfos:      file_api_users_v1_messages_proto_msgTypes,
	}.Build()
	File_api_users_v1_messages_proto = out.File
	file_api_users_v1_messages_proto_goTypes = nil
	file_api_users_v1_messages_proto_depIdxs = nil
}
