// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/users/v1/service.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_users_v1_service_proto protoreflect.FileDescriptor

const file_api_users_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/users/v1/service.proto\x12\fapi.users.v1\x1a\x1bapi/users/v1/messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\x81\x02\n" +
	"\fUsersService\x12x\n" +
	"\fRegisterUser\x12!.api.users.v1.RegisterUserRequest\x1a\".api.users.v1.RegisterUserResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/users/register\x12w\n" +
	"\fRefreshToken\x12!.api.users.v1.RefreshTokenRequest\x1a\".api.users.v1.RefreshTokenResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/users/refreshBL\x92A\x16\x12\x14\n" +
	"\rUsers Service2\x031.0Z1github.com/therenotomorrow/gotes/pkg/api/users/v1b\x06proto3"

var file_api_users_v1_service_proto_goTypes = []any{
	(*RegisterUserRequest)(nil),  // 0: api.users.v1.RegisterUserRequest
	(*RefreshTokenRequest)(nil),  // 1: api.users.v1.RefreshTokenRequest
	(*RegisterUserResponse)(nil), // 2: api.users.v1.RegisterUserResponse
	(*RefreshTokenResponse)(nil), // 3: api.users.v1.RefreshTokenResponse
}
var file_api_users_v1_service_proto_depIdxs = []int32{
	0, // 0: api.users.v1.UsersService.RegisterUser:input_type -> api.users.v1.RegisterUserRequest
	1, // 1: api.users.v1.UsersService.RefreshToken:input_type -> api.users.v1.RefreshTokenRequest
	2, // 2: api.users.v1.UsersService.RegisterUser:output_type -> api.users.v1.RegisterUserResponse
	3, // 3: api.users.v1.UsersService.RefreshToken:output_type -> api.users.v1.RefreshTokenResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_users_v1_service_proto_init() }
func file_api_users_v1_service_proto_init() {
	if File_api_users_v1_service_proto != nil {
		return
	}
	file_api_users_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_users_v1_service_proto_rawDesc), len(file_api_users_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_users_v1_service_proto_goTypes,
		DependencyIndexes: file_api_users_v1_service_proto_depIdxs,
	}.Build()
	File_api_users_v1_service_proto = out.File
	file_api_users_v1_service_proto_goTypes = nil
	file_api_users_v1_service_proto_depIdxs = nil
}
