// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	SelectUserByEmail(ctx context.Context, email string) (*User, error)
	SelectUserByToken(ctx context.Context, token uuid.UUID) (*User, error)
}

var _ Querier = (*Queries)(nil)
