// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: select_user_by_token.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const selectUserByToken = `-- name: SelectUserByToken :one
SELECT id, name, email, password, token, created_at, updated_at
FROM users
WHERE token = $1
`

func (q *Queries) SelectUserByToken(ctx context.Context, token uuid.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, selectUserByToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
