// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: select_user_by_email.sql

package queries

import (
	"context"
)

const selectUserByEmail = `-- name: SelectUserByEmail :one
SELECT id, name, email, password, token, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) SelectUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, selectUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
