// Code generated by protoc-gen-verbose. DO NOT EDIT.
// source: api/chat/v1/messages.proto

package v1

import (
	fmt "fmt"
)

func (x *Header) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Header<CorrelationId=%v>", x.CorrelationId)
}

func (x *Message) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Message<Header=%v, Text=%v>", x.Header, x.Text)
}

func (x *DispatchRequest) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DispatchRequest<Message=%v>", x.Message)
}

func (x *DispatchResponse) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	oneOfVal_Payload := "<nil>"
	switch v := x.GetPayload().(type) {
	case *DispatchResponse_Message:
		oneOfVal_Payload = fmt.Sprintf("%v", v.Message)
	case *DispatchResponse_Status:
		oneOfVal_Payload = fmt.Sprintf("%v", v.Status)
	}
	return fmt.Sprintf("DispatchResponse<Payload=%s>", oneOfVal_Payload)
}
