// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/chat/v1/messages.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Header contains metadata for request tracking and observability.
type Header struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique string used to track a message's lifecycle chatting.
	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// Message represents the core data unit exchanged in a chat session.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata for the message.
	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// The actual text content of the message.
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// DispatchRequest is the envelope for sending a message to the stream.
type DispatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message being dispatched by the client.
	Message       *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *DispatchRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// DispatchResponse is the envelope for receiving data from the stream.
type DispatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The content of the envelope.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*DispatchResponse_Message
	//	*DispatchResponse_Status
	Payload       isDispatchResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *DispatchResponse) GetPayload() isDispatchResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DispatchResponse) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Payload.(*DispatchResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *DispatchResponse) GetStatus() *status.Status {
	if x != nil {
		if x, ok := x.Payload.(*DispatchResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isDispatchResponse_Payload interface {
	isDispatchResponse_Payload()
}

type DispatchResponse_Message struct {
	// The message being dispatched to the client.
	Message *Message `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type DispatchResponse_Status struct {
	// Detailed error status if the dispatch failed.
	Status *status.Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*DispatchResponse_Message) isDispatchResponse_Payload() {}

func (*DispatchResponse_Status) isDispatchResponse_Payload() {}

var File_api_chat_v1_messages_proto protoreflect.FileDescriptor

const file_api_chat_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/chat/v1/messages.proto\x12\vapi.chat.v1\x1a\x1bbuf/validate/validate.proto\x1a\x17google/rpc/status.proto\"/\n" +
	"\x06Header\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\"V\n" +
	"\aMessage\x12+\n" +
	"\x06header\x18\x01 \x01(\v2\x13.api.chat.v1.HeaderR\x06header\x12\x1e\n" +
	"\x04text\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x04R\x04text\"A\n" +
	"\x0fDispatchRequest\x12.\n" +
	"\amessage\x18\x01 \x01(\v2\x14.api.chat.v1.MessageR\amessage\"}\n" +
	"\x10DispatchResponse\x120\n" +
	"\amessage\x18\x01 \x01(\v2\x14.api.chat.v1.MessageH\x00R\amessage\x12,\n" +
	"\x06status\x18\x02 \x01(\v2\x12.google.rpc.StatusH\x00R\x06statusB\t\n" +
	"\apayloadB2Z0github.com/therenotomorrow/gotes/pkg/api/chat/v1b\x06proto3"

var (
	file_api_chat_v1_messages_proto_rawDescOnce sync.Once
	file_api_chat_v1_messages_proto_rawDescData []byte
)

func file_api_chat_v1_messages_proto_rawDescGZIP() []byte {
	file_api_chat_v1_messages_proto_rawDescOnce.Do(func() {
		file_api_chat_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_chat_v1_messages_proto_rawDesc), len(file_api_chat_v1_messages_proto_rawDesc)))
	})
	return file_api_chat_v1_messages_proto_rawDescData
}

var file_api_chat_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_chat_v1_messages_proto_goTypes = []any{
	(*Header)(nil),           // 0: api.chat.v1.Header
	(*Message)(nil),          // 1: api.chat.v1.Message
	(*DispatchRequest)(nil),  // 2: api.chat.v1.DispatchRequest
	(*DispatchResponse)(nil), // 3: api.chat.v1.DispatchResponse
	(*status.Status)(nil),    // 4: google.rpc.Status
}
var file_api_chat_v1_messages_proto_depIdxs = []int32{
	0, // 0: api.chat.v1.Message.header:type_name -> api.chat.v1.Header
	1, // 1: api.chat.v1.DispatchRequest.message:type_name -> api.chat.v1.Message
	1, // 2: api.chat.v1.DispatchResponse.message:type_name -> api.chat.v1.Message
	4, // 3: api.chat.v1.DispatchResponse.status:type_name -> google.rpc.Status
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_chat_v1_messages_proto_init() }
func file_api_chat_v1_messages_proto_init() {
	if File_api_chat_v1_messages_proto != nil {
		return
	}
	file_api_chat_v1_messages_proto_msgTypes[3].OneofWrappers = []any{
		(*DispatchResponse_Message)(nil),
		(*DispatchResponse_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_chat_v1_messages_proto_rawDesc), len(file_api_chat_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_chat_v1_messages_proto_goTypes,
		DependencyIndexes: file_api_chat_v1_messages_proto_depIdxs,
		MessageInfos:      file_api_chat_v1_messages_proto_msgTypes,
	}.Build()
	File_api_chat_v1_messages_proto = out.File
	file_api_chat_v1_messages_proto_goTypes = nil
	file_api_chat_v1_messages_proto_depIdxs = nil
}
