// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/therenotomorrow/gotes/internal/api/notes/v1/ports"
)

// NewMockUnitOfWork creates a new instance of MockUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitOfWork {
	mock := &MockUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnitOfWork is an autogenerated mock type for the UnitOfWork type
type MockUnitOfWork struct {
	mock.Mock
}

type MockUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWork) EXPECT() *MockUnitOfWork_Expecter {
	return &MockUnitOfWork_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) Do(ctx context.Context, work func(store ports.Store) error) error {
	ret := _mock.Called(ctx, work)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(store ports.Store) error) error); ok {
		r0 = returnFunc(ctx, work)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUnitOfWork_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockUnitOfWork_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - work func(store ports.Store) error
func (_e *MockUnitOfWork_Expecter) Do(ctx interface{}, work interface{}) *MockUnitOfWork_Do_Call {
	return &MockUnitOfWork_Do_Call{Call: _e.mock.On("Do", ctx, work)}
}

func (_c *MockUnitOfWork_Do_Call) Run(run func(ctx context.Context, work func(store ports.Store) error)) *MockUnitOfWork_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(store ports.Store) error
		if args[1] != nil {
			arg1 = args[1].(func(store ports.Store) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUnitOfWork_Do_Call) Return(err error) *MockUnitOfWork_Do_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUnitOfWork_Do_Call) RunAndReturn(run func(ctx context.Context, work func(store ports.Store) error) error) *MockUnitOfWork_Do_Call {
	_c.Call.Return(run)
	return _c
}
