// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_note.sql

package commands

import (
	"context"
)

const deleteNote = `-- name: DeleteNote :exec
DELETE
FROM notes
WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteNote, id)
	return err
}
