// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_note.sql

package commands

import (
	"context"
	"time"
)

const insertNote = `-- name: InsertNote :one
INSERT INTO notes (title, content, user_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertNoteParams struct {
	Title     string    `db:"title"`
	Content   string    `db:"content"`
	UserID    *int64    `db:"user_id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

func (q *Queries) InsertNote(ctx context.Context, arg *InsertNoteParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertNote,
		arg.Title,
		arg.Content,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
