// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package commands

import (
	"context"
)

type Querier interface {
	DeleteNote(ctx context.Context, id int64) error
	InsertNote(ctx context.Context, arg *InsertNoteParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
