-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    token      UUID         NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

ALTER TABLE notes
    ADD COLUMN IF NOT EXISTS user_id BIGINT
        REFERENCES users (id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS notes_user_id ON notes (user_id);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP INDEX IF EXISTS notes_user_id;

ALTER TABLE notes
    DROP COLUMN IF EXISTS user_id;

DROP TABLE IF EXISTS users;
-- +goose StatementEnd
