// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: select_notes_by_user.sql

package queries

import (
	"context"
)

const selectNotesByUser = `-- name: SelectNotesByUser :many
SELECT id, title, content, user_id, created_at, updated_at
FROM notes
WHERE user_id = $1
ORDER BY notes.id
`

func (q *Queries) SelectNotesByUser(ctx context.Context, userID *int64) ([]*Note, error) {
	rows, err := q.db.Query(ctx, selectNotesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
