// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: select_note.sql

package queries

import (
	"context"
)

const selectNote = `-- name: SelectNote :one
SELECT id, title, content, user_id, created_at, updated_at
FROM notes
WHERE id = $1
`

func (q *Queries) SelectNote(ctx context.Context, id int64) (*Note, error) {
	row := q.db.QueryRow(ctx, selectNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
