// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/types/error.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode represents a readable error classification.
type ErrorCode int32

const (
	// Unknown or unspecified error.
	ErrorCode_ERROR_CODE_UNKNOWN ErrorCode = 0
	// The provided identifier is invalid or malformed.
	ErrorCode_ERROR_CODE_INVALID_ID ErrorCode = 1
	// The provided email address is invalid.
	ErrorCode_ERROR_CODE_INVALID_EMAIL ErrorCode = 2
	// The provided password does not meet validation requirements.
	ErrorCode_ERROR_CODE_INVALID_PASSWORD ErrorCode = 3
	// The provided title is invalid.
	ErrorCode_ERROR_CODE_INVALID_TITLE ErrorCode = 4
	// The provided content is invalid.
	ErrorCode_ERROR_CODE_INVALID_CONTENT ErrorCode = 5
	// The requested entity does not exist.
	ErrorCode_ERROR_CODE_ENTITY_NOT_FOUND ErrorCode = 6
	// The caller does not have permission to perform the requested operation.
	ErrorCode_ERROR_CODE_PERMISSION_DENIED ErrorCode = 7
	// Internal server error.
	ErrorCode_ERROR_CODE_INTERNAL ErrorCode = 99
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_UNKNOWN",
		1:  "ERROR_CODE_INVALID_ID",
		2:  "ERROR_CODE_INVALID_EMAIL",
		3:  "ERROR_CODE_INVALID_PASSWORD",
		4:  "ERROR_CODE_INVALID_TITLE",
		5:  "ERROR_CODE_INVALID_CONTENT",
		6:  "ERROR_CODE_ENTITY_NOT_FOUND",
		7:  "ERROR_CODE_PERMISSION_DENIED",
		99: "ERROR_CODE_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNKNOWN":           0,
		"ERROR_CODE_INVALID_ID":        1,
		"ERROR_CODE_INVALID_EMAIL":     2,
		"ERROR_CODE_INVALID_PASSWORD":  3,
		"ERROR_CODE_INVALID_TITLE":     4,
		"ERROR_CODE_INVALID_CONTENT":   5,
		"ERROR_CODE_ENTITY_NOT_FOUND":  6,
		"ERROR_CODE_PERMISSION_DENIED": 7,
		"ERROR_CODE_INTERNAL":          99,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_types_error_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_api_types_error_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_types_error_proto_rawDescGZIP(), []int{0}
}

// Error represents a structured error returned by the API.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Readable error code.
	Code ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=api.types.ErrorCode" json:"code,omitempty"`
	// Human-readable explanation of the error.
	//
	// Intended for debugging or displaying to end users.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_api_types_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_api_types_error_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNKNOWN
}

func (x *Error) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_api_types_error_proto protoreflect.FileDescriptor

const file_api_types_error_proto_rawDesc = "" +
	"\n" +
	"\x15api/types/error.proto\x12\tapi.types\"I\n" +
	"\x05Error\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.api.types.ErrorCodeR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*\x97\x02\n" +
	"\tErrorCode\x12\x16\n" +
	"\x12ERROR_CODE_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15ERROR_CODE_INVALID_ID\x10\x01\x12\x1c\n" +
	"\x18ERROR_CODE_INVALID_EMAIL\x10\x02\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_PASSWORD\x10\x03\x12\x1c\n" +
	"\x18ERROR_CODE_INVALID_TITLE\x10\x04\x12\x1e\n" +
	"\x1aERROR_CODE_INVALID_CONTENT\x10\x05\x12\x1f\n" +
	"\x1bERROR_CODE_ENTITY_NOT_FOUND\x10\x06\x12 \n" +
	"\x1cERROR_CODE_PERMISSION_DENIED\x10\a\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10cB0Z.github.com/therenotomorrow/gotes/pkg/api/typesb\x06proto3"

var (
	file_api_types_error_proto_rawDescOnce sync.Once
	file_api_types_error_proto_rawDescData []byte
)

func file_api_types_error_proto_rawDescGZIP() []byte {
	file_api_types_error_proto_rawDescOnce.Do(func() {
		file_api_types_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_types_error_proto_rawDesc), len(file_api_types_error_proto_rawDesc)))
	})
	return file_api_types_error_proto_rawDescData
}

var file_api_types_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_types_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_types_error_proto_goTypes = []any{
	(ErrorCode)(0), // 0: api.types.ErrorCode
	(*Error)(nil),  // 1: api.types.Error
}
var file_api_types_error_proto_depIdxs = []int32{
	0, // 0: api.types.Error.code:type_name -> api.types.ErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_types_error_proto_init() }
func file_api_types_error_proto_init() {
	if File_api_types_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_types_error_proto_rawDesc), len(file_api_types_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_types_error_proto_goTypes,
		DependencyIndexes: file_api_types_error_proto_depIdxs,
		EnumInfos:         file_api_types_error_proto_enumTypes,
		MessageInfos:      file_api_types_error_proto_msgTypes,
	}.Build()
	File_api_types_error_proto = out.File
	file_api_types_error_proto_goTypes = nil
	file_api_types_error_proto_depIdxs = nil
}
