// Code generated by protoc-gen-verbose. DO NOT EDIT.
// source: api/types/error.proto

package types

import (
	fmt "fmt"
)

func (x *Error) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Error<Code=%v, Reason=%v>", x.Code, x.Reason)
}
