// Code generated by protoc-gen-verbose. DO NOT EDIT.
// source: api/types/id.proto

package types

import (
	fmt "fmt"
)

func (x *ID) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ID<Value=%v>", x.Value)
}
