// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/therenotomorrow/gotes/internal/api/metrics/v1/entities"
)

// NewMockMetricsRepository creates a new instance of MockMetricsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsRepository {
	mock := &MockMetricsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricsRepository is an autogenerated mock type for the MetricsRepository type
type MockMetricsRepository struct {
	mock.Mock
}

type MockMetricsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsRepository) EXPECT() *MockMetricsRepository_Expecter {
	return &MockMetricsRepository_Expecter{mock: &_m.Mock}
}

// Download provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) Download(ctx context.Context) ([]entities.Metrics, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 []entities.Metrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entities.Metrics, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entities.Metrics); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Metrics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricsRepository_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockMetricsRepository_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMetricsRepository_Expecter) Download(ctx interface{}) *MockMetricsRepository_Download_Call {
	return &MockMetricsRepository_Download_Call{Call: _e.mock.On("Download", ctx)}
}

func (_c *MockMetricsRepository_Download_Call) Run(run func(ctx context.Context)) *MockMetricsRepository_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricsRepository_Download_Call) Return(metricss []entities.Metrics, err error) *MockMetricsRepository_Download_Call {
	_c.Call.Return(metricss, err)
	return _c
}

func (_c *MockMetricsRepository_Download_Call) RunAndReturn(run func(ctx context.Context) ([]entities.Metrics, error)) *MockMetricsRepository_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) Upload(ctx context.Context, metrics entities.Metrics) error {
	ret := _mock.Called(ctx, metrics)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Metrics) error); ok {
		r0 = returnFunc(ctx, metrics)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricsRepository_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockMetricsRepository_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - metrics entities.Metrics
func (_e *MockMetricsRepository_Expecter) Upload(ctx interface{}, metrics interface{}) *MockMetricsRepository_Upload_Call {
	return &MockMetricsRepository_Upload_Call{Call: _e.mock.On("Upload", ctx, metrics)}
}

func (_c *MockMetricsRepository_Upload_Call) Run(run func(ctx context.Context, metrics entities.Metrics)) *MockMetricsRepository_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Metrics
		if args[1] != nil {
			arg1 = args[1].(entities.Metrics)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricsRepository_Upload_Call) Return(err error) *MockMetricsRepository_Upload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricsRepository_Upload_Call) RunAndReturn(run func(ctx context.Context, metrics entities.Metrics) error) *MockMetricsRepository_Upload_Call {
	_c.Call.Return(run)
	return _c
}
