// Code generated by protoc-gen-verbose. DO NOT EDIT.
// source: api/notes/v1/messages.proto

package v1

import (
	fmt "fmt"
)

func (x *Note) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Note<Id=%v, Title=%v, Content=%v, CreatedAt=%v, UpdatedAt=%v>", x.Id, x.Title, x.Content, x.CreatedAt, x.UpdatedAt)
}

func (x *ListNotesRequest) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListNotesRequest<>")
}

func (x *ListNotesResponse) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListNotesResponse<Notes=%v>", x.Notes)
}

func (x *RetrieveNoteRequest) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RetrieveNoteRequest<Id=%v>", x.Id)
}

func (x *RetrieveNoteResponse) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RetrieveNoteResponse<Note=%v>", x.Note)
}

func (x *CreateNoteRequest) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateNoteRequest<Title=%v, Content=%v>", x.Title, x.Content)
}

func (x *CreateNoteResponse) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateNoteResponse<Note=%v>", x.Note)
}

func (x *DeleteNoteRequest) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteNoteRequest<Id=%v>", x.Id)
}

func (x *DeleteNoteResponse) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteNoteResponse<>")
}

func (x *Event) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Event<Id=%v, Type=%v, NoteId=%v, EventTime=%v>", x.Id, x.Type, x.NoteId, x.EventTime)
}

func (x *Unread) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Unread<Events=%v>", x.Events)
}

func (x *SubscribeToEventsRequest) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SubscribeToEventsRequest<>")
}

func (x *SubscribeToEventsResponse) Verbose() string {
	if x == nil {
		return "<nil>"
	}
	oneOfVal_Payload := "<nil>"
	switch v := x.GetPayload().(type) {
	case *SubscribeToEventsResponse_Event:
		oneOfVal_Payload = fmt.Sprintf("%v", v.Event)
	case *SubscribeToEventsResponse_Unread:
		oneOfVal_Payload = fmt.Sprintf("%v", v.Unread)
	}
	return fmt.Sprintf("SubscribeToEventsResponse<Payload=%s>", oneOfVal_Payload)
}
