// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/notes/v1/service.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_notes_v1_service_proto protoreflect.FileDescriptor

const file_api_notes_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/notes/v1/service.proto\x12\fapi.notes.v1\x1a\x1bapi/notes/v1/messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xd1\x04\n" +
	"\fNotesService\x12c\n" +
	"\tListNotes\x12\x1e.api.notes.v1.ListNotesRequest\x1a\x1f.api.notes.v1.ListNotesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/notes\x12w\n" +
	"\fRetrieveNote\x12!.api.notes.v1.RetrieveNoteRequest\x1a\".api.notes.v1.RetrieveNoteResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/notes/{id.value}\x12i\n" +
	"\n" +
	"CreateNote\x12\x1f.api.notes.v1.CreateNoteRequest\x1a .api.notes.v1.CreateNoteResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/notes\x12q\n" +
	"\n" +
	"DeleteNote\x12\x1f.api.notes.v1.DeleteNoteRequest\x1a .api.notes.v1.DeleteNoteResponse\" \x82\xd3\xe4\x93\x02\x1a*\x18/api/v1/notes/{id.value}\x12\x84\x01\n" +
	"\x11SubscribeToEvents\x12&.api.notes.v1.SubscribeToEventsRequest\x1a'.api.notes.v1.SubscribeToEventsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/notes/events0\x01B{\x92AE\x12\x14\n" +
	"\rNotes Service2\x031.0Z\x1f\n" +
	"\x1d\n" +
	"\x06Bearer\x12\x13\b\x02\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00Z1github.com/therenotomorrow/gotes/pkg/api/notes/v1b\x06proto3"

var file_api_notes_v1_service_proto_goTypes = []any{
	(*ListNotesRequest)(nil),          // 0: api.notes.v1.ListNotesRequest
	(*RetrieveNoteRequest)(nil),       // 1: api.notes.v1.RetrieveNoteRequest
	(*CreateNoteRequest)(nil),         // 2: api.notes.v1.CreateNoteRequest
	(*DeleteNoteRequest)(nil),         // 3: api.notes.v1.DeleteNoteRequest
	(*SubscribeToEventsRequest)(nil),  // 4: api.notes.v1.SubscribeToEventsRequest
	(*ListNotesResponse)(nil),         // 5: api.notes.v1.ListNotesResponse
	(*RetrieveNoteResponse)(nil),      // 6: api.notes.v1.RetrieveNoteResponse
	(*CreateNoteResponse)(nil),        // 7: api.notes.v1.CreateNoteResponse
	(*DeleteNoteResponse)(nil),        // 8: api.notes.v1.DeleteNoteResponse
	(*SubscribeToEventsResponse)(nil), // 9: api.notes.v1.SubscribeToEventsResponse
}
var file_api_notes_v1_service_proto_depIdxs = []int32{
	0, // 0: api.notes.v1.NotesService.ListNotes:input_type -> api.notes.v1.ListNotesRequest
	1, // 1: api.notes.v1.NotesService.RetrieveNote:input_type -> api.notes.v1.RetrieveNoteRequest
	2, // 2: api.notes.v1.NotesService.CreateNote:input_type -> api.notes.v1.CreateNoteRequest
	3, // 3: api.notes.v1.NotesService.DeleteNote:input_type -> api.notes.v1.DeleteNoteRequest
	4, // 4: api.notes.v1.NotesService.SubscribeToEvents:input_type -> api.notes.v1.SubscribeToEventsRequest
	5, // 5: api.notes.v1.NotesService.ListNotes:output_type -> api.notes.v1.ListNotesResponse
	6, // 6: api.notes.v1.NotesService.RetrieveNote:output_type -> api.notes.v1.RetrieveNoteResponse
	7, // 7: api.notes.v1.NotesService.CreateNote:output_type -> api.notes.v1.CreateNoteResponse
	8, // 8: api.notes.v1.NotesService.DeleteNote:output_type -> api.notes.v1.DeleteNoteResponse
	9, // 9: api.notes.v1.NotesService.SubscribeToEvents:output_type -> api.notes.v1.SubscribeToEventsResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_notes_v1_service_proto_init() }
func file_api_notes_v1_service_proto_init() {
	if File_api_notes_v1_service_proto != nil {
		return
	}
	file_api_notes_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notes_v1_service_proto_rawDesc), len(file_api_notes_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_notes_v1_service_proto_goTypes,
		DependencyIndexes: file_api_notes_v1_service_proto_depIdxs,
	}.Build()
	File_api_notes_v1_service_proto = out.File
	file_api_notes_v1_service_proto_goTypes = nil
	file_api_notes_v1_service_proto_depIdxs = nil
}
